### ISSUE TITLE
Generation of Tags property

### ISSUE THREAD

**Issue by gzoug** [Jaxelr/Nancy.Metadata.OpenApi#3]
Hi @Jaxelr,
The json generated, exposes the Tags property as array of strings which is wrong according to  
OpenApi [tag definition](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#tagObject). (I'm refering to the root [OpenAPI document](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#openapi-object) )

We could have another one model for Tags, instead of passing string[] to the constructor,  right?

**Comment by Jaxelr** [comment]
Indeed, thats a bug and you are correct.

**Comment by Jaxelr** [comment]
Thanks for providing the PR #4 to fix this
