### ISSUE TITLE
JsonSchema4 was renamed to JsonSchema in NJsonSchema 10.x

### ISSUE THREAD

**Issue by softexpert** [Jaxelr/Nancy.Metadata.OpenApi#72]
Hi Jaxel,
There are some changes in the new 10.x NJsonSchema release.

# Describe the bug

Latest NJsonSchema release renamed JsonSchema4 to JsonSchema.

## Steps to reproduce

Import NJsonSchema v10.x and try to compile.

## Expected behavior

Should compile without warnings.

- Dotnet version: [dotnet472]
- Library version: [latest master branch]

# Solution
Rename JsonSchema4 to JsonSchema in:
- OpenApiDocsModuleBase.cs, 
- Component.cs,
- TypeNameGenerator.cs (also add using NJsonSchema.Generation;),
- SchemaCache.cs,
- SchemaGenerator.cs

Thank you !

Best regards,
SoftExpert

**Comment by Jaxelr** [comment]
Thanks for opening the issue, I'm currently testing the [swagger version of this lib](https://github.com/Jaxelr/Nancy.Metadata.Swagger.Core) with version 10 of the njson schema lib. After releasing that package, i will work on this change. I'm guessing i will release it by the end of this week.

**Comment by Jaxelr** [comment]
Published on myget version 0.9.0 that includes the integration to njsonschema 10. During the day i will do a few tests and publish on nuget between today and tomorrow.

**Comment by Jaxelr** [comment]
Posted on nuget. Closing issue.
